spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create
      show_sql: true
      format_sql: true
      use_sql_comments: true
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console.enabled: true
#  sql:
#    init:
#      mode: ALWAYS
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
print:
  tripleCity:
    count: 10