server:
  port: 8080
  shutdown: graceful
  error:
    whitelabel:
      enabled: false
spring:
  profiles:
    active: dev
  application:
    name: triple-travel
  jackson:
    serialization:
      INDENT_OUTPUT: true