---- CATEGORY TABLE
INSERT INTO CATEGORY(CATEGORY_CODE, CATEGORY_NAME, CATEGORY_ENG_NAME, PARENT_CATEGORY_CODE, DOMESTIC_OVERSEAS_DIVISION, CREATE_AT, UPDATE_AT) VALUES ('DNA', '동남아시아', 'Southeast Asia', '', 'O', '20221026', '20221026');
INSERT INTO CATEGORY(CATEGORY_CODE, CATEGORY_NAME, CATEGORY_ENG_NAME, PARENT_CATEGORY_CODE, DOMESTIC_OVERSEAS_DIVISION, CREATE_AT, UPDATE_AT) VALUES ('ASA', '아시아', 'Asia', '', 'O', '20221026', '20221026');
INSERT INTO CATEGORY(CATEGORY_CODE, CATEGORY_NAME, CATEGORY_ENG_NAME, PARENT_CATEGORY_CODE, DOMESTIC_OVERSEAS_DIVISION, CREATE_AT, UPDATE_AT) VALUES ('America', '아메리카', 'AME', '', 'O', '20221026', '20221026');
INSERT INTO CATEGORY(CATEGORY_CODE, CATEGORY_NAME, CATEGORY_ENG_NAME, PARENT_CATEGORY_CODE, DOMESTIC_OVERSEAS_DIVISION, CREATE_AT, UPDATE_AT) VALUES ('JPN', '일본', 'Japan', 'ASA', 'O', '20221026', '20221026');
INSERT INTO CATEGORY(CATEGORY_CODE, CATEGORY_NAME, CATEGORY_ENG_NAME, PARENT_CATEGORY_CODE, DOMESTIC_OVERSEAS_DIVISION, CREATE_AT, UPDATE_AT) VALUES ('KOR', '한국', 'Korea', 'ASA', 'O', '20221026', '20221026');
INSERT INTO CATEGORY(CATEGORY_CODE, CATEGORY_NAME, CATEGORY_ENG_NAME, PARENT_CATEGORY_CODE, DOMESTIC_OVERSEAS_DIVISION, CREATE_AT, UPDATE_AT) VALUES ('USA', '미국', 'USA', 'AME', 'O', '20221026', '20221026');
INSERT INTO CATEGORY(CATEGORY_CODE, CATEGORY_NAME, CATEGORY_ENG_NAME, PARENT_CATEGORY_CODE, DOMESTIC_OVERSEAS_DIVISION, CREATE_AT, UPDATE_AT) VALUES ('THA', '태국', 'Thailand', 'ASA', 'O', '20221026', '20221026');

-- CITY TABLE
INSERT INTO CITY(CITY_CODE, CITY_NAME, CITY_ENG_NAME) VALUES ('JPN_KYT', '교토', 'KYOTO');
INSERT INTO CITY(CITY_CODE, CITY_NAME, CITY_ENG_NAME) VALUES ('JPN_OSK', '오사카', 'OSAKA');
INSERT INTO CITY(CITY_CODE, CITY_NAME, CITY_ENG_NAME) VALUES ('KOR_SEO', '서울', 'SEOUL');
INSERT INTO CITY(CITY_CODE, CITY_NAME, CITY_ENG_NAME) VALUES ('KOR_INC', '인천', 'INCHEN');
INSERT INTO CITY(CITY_CODE, CITY_NAME, CITY_ENG_NAME) VALUES ('KOR_BUS', '부산', 'Busan');
INSERT INTO CITY(CITY_CODE, CITY_NAME, CITY_ENG_NAME) VALUES ('KOR_JE', '제주도', 'Jeju Island');
INSERT INTO CITY(CITY_CODE, CITY_NAME, CITY_ENG_NAME) VALUES ('USA_LA', '로스앤잴러스', 'LosAngeles');
INSERT INTO CITY(CITY_CODE, CITY_NAME, CITY_ENG_NAME) VALUES ('USA_SLA', '라스베가스', 'Lasvegas');
INSERT INTO CITY(CITY_CODE, CITY_NAME, CITY_ENG_NAME) VALUES ('USA_LYC', '뉴욕', 'NewYorkCity');
INSERT INTO CITY(CITY_CODE, CITY_NAME, CITY_ENG_NAME) VALUES ('USA_SEA', '시애틀', 'Seattle');
INSERT INTO CITY(CITY_CODE, CITY_NAME, CITY_ENG_NAME) VALUES ('USA_SF', '샌프란시스코', 'San Francisco');
INSERT INTO CITY(CITY_CODE, CITY_NAME, CITY_ENG_NAME) VALUES ('USA_BOS', '보스턴', 'Boston');
INSERT INTO CITY(CITY_CODE, CITY_NAME, CITY_ENG_NAME) VALUES ('THA_CHM', '치앙마이', 'Chiang Mai');
INSERT INTO CITY(CITY_CODE, CITY_NAME, CITY_ENG_NAME) VALUES ('THA_BAN', '방콕', 'Bangkok');

-- USER TABLE
INSERT INTO USERS(USER_ID, USER_NAME) VALUES ('JYPARK', '박준영');
INSERT INTO USERS(USER_ID, USER_NAME) VALUES ('HONG', '홍길동');
INSERT INTO USERS(USER_ID, USER_NAME) VALUES ('KIM', '김길동');
INSERT INTO USERS(USER_ID, USER_NAME) VALUES ('LEE', '이길동');